### PR TITLE
tidied up apache confs

### LINKED ISSUE #19: tidy up apache confs
Apache site configs should be tidied up and consolidated.

Also @l-arnold I know that you are really keen on your tklwebcp page. I would really like to understand better what you use it for and why. TBH it doesn't really make a lot of sense to me but it's possible I'm missing something...

### PR DESCRIPTION
**Pull request by JedMeister**
closes #19

### CODE REVIEW

**Comment by JedMeister** [comment]
rm test cgi file too...

**Comment by l-arnold** [comment]
Tomorrow I can do a build of this to see if we are routing properly.

Critical that the whole ODOO system goes to SSL only.  You can escape that by allowing ODOO over 8069 in openerp-server.conf, but APACHE needs to Force SSL and not complaine or do anything but jump to https if they type http: at the start.

System was started with the LAPP template but the ODOO proxy was added.  Can't remember what it was modeled after, but I think it was mostly "wide studies".  Again, it was a while ago and there is some early history I am sure to where it came from in Git.

**Comment by JedMeister** [comment]
Have a look at what I did (via the "[Files changed](https://github.com/DocCyblade/tkl-odoo/pull/20/files)" link towards the top of the page. Most of your comments are answered if you look at that.

Basically I removed the empty file, merged the 2 odoo/openerp apache conf files and removed some superfluous stuff, oh and I renamed your webcp conf file just to make it more descriptive of what it is.

**Comment by l-arnold** [comment]
@JedMeister   ...  Just (sort of up) from Sleep.  It occured to me that you had not seen the progress and report on the Hot Fix yesterday.  It was really a fantastic set that Doc had worked through.  Since it went so well I closed the issue infact.

Do check this out:  Pictures tell the story.  https://github.com/DocCyblade/tkl-odoo/issues/13

**Comment by l-arnold** [comment]
Ok,  Found the "response' and summary of the "files changed" from Jeremy.  Thanks for the clarification.  WebCp is more descriptive.  The empty file was generated actually in the first move of Lapp to Jessie.  I recall seeing that somehow.  I believe that TKLDEV did that but not entirely clear at this point 

I was responding to the email from github directly via "view it online".  I should have looked at the changes last night.  It was late.

**Pull request merged**
