### PR TITLE
v14-READY

### PR DESCRIPTION
**Pull request by DocCyblade**
After many hours of scripting and testing we are proud to present our TurnKey Linux Odoo appliance for consideration to be added to the "Official Library" and to the masses! 

Special thanks to @l-arnold  for the great start, you are a testing machine! Also to @JedMeister for mentoring me and putting up with us spamming your email box with GitHub emails!

Lets all celebrate with :beers:  for everyone!

### CODE REVIEW

**Comment by DocCyblade** [comment]
@l-arnold - Please do the honors and press that "Merge pull request" button!!!

**Comment by l-arnold** [comment]
Merge pull it is.  Thanks for the great work Ken!

**Comment by DocCyblade** [comment]
And there was much rejoicing :tada: :balloon: :cake: :beers:

**Comment by l-arnold** [comment]
:beers: it IS.  :balloon:  :earth_americas:

**Comment by DocCyblade** [comment]
Just opened a Guinness :beer:  I have been saving for a special occasion. So as @JedMeister  might (probably) would say "Cheers mate!"

**Comment by JedMeister** [comment]
Congrats guys. Well earned :beers:! You pair are a team to be reckoned with! :+1: 

And I would say "Cheers mate"! :smile:

**Comment by l-arnold** [comment]
Cheers Jeremy! Cheers Ken.

Czechvar (ie Budvwar in most of thethe world), poured and half down!

**Pull request merged**
