### PR TITLE
tweak changelog

### PR DESCRIPTION
**Pull request by JedMeister**
I just tweaked the changelog. 

The first bit is only suggested. I just thought a slightly different layout might work better. 

Also happy for you guys to have all the glory for this build. I've only given advice/opinion mostly (and been a PITA no doubt! :stuck_out_tongue: )

Re removal of the reference to LAPP changelog: I totally get where you're coming from and that would be my preference too but Alon decided that all the apps just reference Core and make individual note of any special changes in LAMP/LAPP so this keeps it consistent with the other appliances...

### CODE REVIEW

**Comment by DocCyblade** [comment]
Is this one of the 'unwritten rules" you spoke of?

So if we base another app off another such as lapp in the future, just mention core and, what is considered special changes? Such as Adminer and SSL Harding? I saw this in another app change log. That now makes sense to me why they had that in there.

**Comment by DocCyblade** [comment]
Looks good to me, @l-arnold I'll let you take a look as well and comment

**Comment by JedMeister** [comment]
> Is this one of the 'unwritten rules" you spoke of?

Yeah seems so... :smile: 

You could certainly add mention of Adminer...

**Comment by DocCyblade** [comment]
Well if this is the first release, and we do say it's built on Lapp, that's implied. The next version we would include anything special that changed in LAPP along with. Makes sense to me now. I'll leave it as is

**Comment by l-arnold** [comment]
This looks fine.  I will add however that my original start came from "tklcarlos" , ie on github CLVsol/tkl-odoo

Carlos made a strong effort on this and diverted into making Patches where he could Mod a Cloud install of Lapp for instance.

He did some great work.  I did try a few times to get him to come in on this but did not hear back.

**Comment by DocCyblade** [comment]
@l-arnold did he help you with your repo? I did not see any commits by him?

**Comment by l-arnold** [comment]
No.  However my "starting" code base came from him.  He had actually pointed me towards his "patch system" but I found the other repository and it looked like more the direction.  I didn't "fork" per say.  Just used it as a base.  We did "linkin" the other day and I expect he would come in once this goes into the library.  He does some very interesting work.  Mostly focused towards the medical industry.

Certainly comfortable w/ a citation his way.  It is in my original "readme" for sure..

**Comment by DocCyblade** [comment]
I'm OK to add him if you would like just let me know

**Comment by l-arnold** [comment]
Why don't we say 
Inspired by the original efforts of Carlos Vercelino on Github at: CLVsol/tkl-odoo

**Comment by DocCyblade** [comment]
Sounds good. I'll approve the request and then make the changes

**Pull request merged**
