### PR TITLE
Release Candidate 1 (v14-RC1)

### PR DESCRIPTION
**Pull request by DocCyblade**
Release Candidate 1 for v14

Everything should be stable

### CODE REVIEW

**Comment by DocCyblade** [comment]
Will approve this once all bugs have been closed

**Comment by l-arnold** [comment]
Ok new build going on now.

Thanks Ken!

**Comment by l-arnold** [comment]
Seems all bugs are closed (incl #47)

**Comment by l-arnold** [comment]
Changes overall and documentation in openerp-server.conf files all look very good.

**Pull request merged**
